redis:
  host: redis-database-master-service.redis-database.svc.cluster.local
  port: 6379
  cache_db: 1
  queue_db: 2
  rate_limit_db: 3
  user: scraper_user
  client_cache_max_age: 30

rate_limiting:
  default: 100/minute
  auth: 5/minute
