---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: recipe-scraper-ingress-recipe-scraper-local
  namespace: recipe-scraper
spec:
  hostnames:
  - recipe-scraper.local
  - sous-chef-proxy.local
  parentRefs:
  - name: kong
    namespace: kong
  rules:
  - backendRefs:
    - name: recipe-scraper
      port: 8000
    matches:
    - path:
        type: PathPrefix
        value: /api/recipe-scraper
status:
  parents: []
