# ==============================================================================
# ServiceAccount
# ==============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recipe-scraper-service
  labels:
    app.kubernetes.io/name: recipe-scraper-service
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
