# ==============================================================================
# Namespace - Staging
# ==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: recipe-scraper-staging
  labels:
    app.kubernetes.io/name: recipe-scraper-service
    environment: staging
